# Generated by Django 6.0.3 on 2026-04-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('track', models.CharField(choices=[('Django', 'Django'), ('SpringBoot', 'SpringBoot'), ('Frontend', 'Frontend'), ('Design', 'Design')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'week7_lion',
            },
        ),
    ]
