# Generated by Django 4.2.29 on 2026-05-08 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lions', '0002_alter_lion_track_task_tag_lionprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lionprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
