# Generated by Django 4.2.29 on 2026-05-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lion',
            name='track',
            field=models.CharField(blank=True, choices=[('Django', 'Django'), ('SpringBoot', 'SpringBoot'), ('Frontend', 'Frontend')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='lions.lion')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lions', models.ManyToManyField(blank=True, related_name='tags', to='lions.lion')),
            ],
        ),
        migrations.CreateModel(
            name='LionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='lions.lion')),
            ],
        ),
    ]
