# Generated by Django 4.2.29 on 2026-04-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('track', models.CharField(blank=True, choices=[('frontend', '프론트엔드'), ('backend', '백엔드'), ('design', '디자인'), ('planning', '기획')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
