# Generated by Django 6.0.3 on 2026-05-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lions', '0002_lionprofile_tag_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
    ]
