# Generated by Django 6.0.3 on 2026-04-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Lion',
        ),
        migrations.AlterModelTable(
            name='lion',
            table='lions',
        ),
    ]
