# Generated by Django 6.0.3 on 2026-04-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_basic', '0003_lionprofile_tag_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lion',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='lionprofile',
            name='github_rul',
        ),
        migrations.AddField(
            model_name='lionprofile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='lion',
            name='track',
            field=models.CharField(choices=[('django', 'Django'), ('springboot', 'SpringBoot'), ('frontend', 'Frontend')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='lions',
            field=models.ManyToManyField(blank=True, to='orm_basic.lion'),
        ),
    ]
